#!/bin/bash
# Generate a memorable 8.3 password.
# Generate a four-word pass-phrase.

memorable_password() {
   length=${1?-Password length required}
   VOWELS="aeiou"
   CONSONANTS="bcdfghjklmnpqrstvwxyz"

   n=1
   while [ "${n}" -le "$length" ]; do
      # $RANDOM generates a random number from 0 to 32767
      # $RANDOM % n generates a random number from 0 to n-1
      # String-slicing in Bash is zero-indexed,
      # so here we take one consonant and one vowel.
      username="$username${CONSONANTS:$(($RANDOM % ${#CONSONANTS})):1}"
      username="$username${VOWELS:$(($RANDOM % ${#VOWELS})):1}"
      let n+=2
   done
   username=${username:0:$length}
   echo -n $username
}

random_number_string() {
   length=${1?-Random number string length required}
   string=000000000000$(($RANDOM % 1000))
   string=${string:(-$length)}
   echo -n $string
}

echo $(memorable_password 8)
echo $(memorable_password 8)$(random_number_string 3)

# Also generate a 4-word pass-phrase
passphrase=$(look . | grep -E "^[a-z]{5,9}$" | shuf | head -4 | tr '\n' ' ')
echo $passphrase
echo $passphrase | sed 's# ##g'

