#!/bin/sh
# https://www.linuxquestions.org/questions/linux-general-1/lq-poll-what%27s-your-favorite-linux-terminal-trick-4175654014/#post5995677
#
#    $ path
#    ls: cannot access '/home/billy/R/usr/bin': No such file or directory
#    ls: cannot access '/home/billy/R/bin': No such file or directory
#         1  /bin
#         2  /home/billy/bin
#         3  /home/billy/go
#         4  /home/billy/usr/bin
#         5  /sbin
#         6  /usr/bin
#         7  /usr/games
#         8  /usr/local/bin
#         9  /usr/local/games
#        10  /usr/sbin

IFS=:
ls -1d $PATH | nl

