#!/bin/sh

set -e

candidate=$(which $1)
while [ -L "$candidate" ]; do
   ls -lh --color $candidate
   path=$(dirname $candidate)
   candidate=$(readlink $candidate)
   if [ "$(basename $candidate)" = "$candidate" ]
      then candidate="$path/$candidate"
   fi
done
ls -lh --color $candidate
file $candidate

