#!/bin/bash

set -e

cleanup() {
   test -n "$tmpfile" && rm "$tmpfile"
}
trap cleanup EXIT

basename=$(basename "$1")
tmpfile=$(mktemp -t "$basename.XXXXXX")

antiword "$1" > "$tmpfile"
terminal-vim "$tmpfile"

